camunda:
  admin-user:
    id: a
    password: a
  bpm:
    database:
      type: postgres
    table-prefix: camunda.
    schema-update: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    #DB connection:
    url: jdbc:postgresql://localhost:5432/sbp
    username: sbp
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#logging.level.com.example.feign.GitFeign: DEBUG
#feign.client.config.default.loggerLevel: full

app:
  sample:
    config:
      keys:
        loanNumber: 'loanNumber'
        loanNumbers: 'loanNumbers'
        proposalRequest: 'proposalRequestDto'
        proposalResponse: 'proposalResponseDto'
        report: 'report'

db:
  iwonosql:
    connection:
      url: https://api.github.com/repos/<USER_NAME>/<REPO_NAME>
      auth:
        key: <PERSONAL_ACCESS_TOKEN>