version: '3.7'

services:
  postgres:
    image: postgres:13-alpine3.14
    container_name: sample-bpm-postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sbp
      - POSTGRES_DB=sbp
      - POSTGRES_HOST_AUTH_METHOD=trust

  zookeeper:
    container_name: sample-bpm-mb-zk
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: sample-bpm-mb
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost