version: '3.7'

services:
  sample-bpm-project:
    image: postgres:11-alpine
    container_name: sample-bpm-postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sbp
      - POSTGRES_DB=sbp
      - POSTGRES_HOST_AUTH_METHOD=trust